apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nate-agent
  name: api-deployment
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api-deployment
        image: nhowell02/agentserver:latest
        ports:
        - containerPort: 8080
