apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nate-agent
  name: client-deployment
  labels:
    app: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
      - name: client-deployment
        image: nhowell02/agentclient:latest
        ports:
        - containerPort: 80
