apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  namespace: nate-agent
spec:
  rules:
  - host: "client.nagent.duckdns.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zas-grafana-svc
            port:
              number: 80