apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  namespace: nate-agent
spec:
  selector:
    app: mcp-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
