name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          # Use short SHA as tag or increment manually
          echo "TAG=latest" >> $GITHUB_ENV
          echo "COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # ---------------- Client ----------------
      - name: Build client image
        run: |
          docker build -f AgentFront/Agent.Api/Dockerfile \
          -t nhowell02/agentclient:$TAG \
          ./AgentFront/Agent.Api


      - name: Push client image
        run: |
          docker push nhowell02/agentclient:$TAG

      # ---------------- Server ----------------
      - name: Build server image
        run: |
          docker build \
            -t nhowell02/agentserver:$TAG \
            .

      - name: Push server image
        run: |
          docker push nhowell02/agentserver:$TAG
  
  pushtokubernetes:
        runs-on: self-hosted
        needs: [build-and-push]
        steps:
        - name: print file structure
          run: ls
        - name: deploy to kubernetes
          run: |
            export NAMESPACE=${{github.event.pull_request.number}}-
            export SUBDOMAIN=${{github.event.pull_request.number}}.
            export BUILD_NUMBER=${{github.run_id}}

            for FILE in *
            do
              cat "$FILE" | envsubst | kubectl apply -f -
            done
